datagrid:
    # contact groups grid, shown on orocrm_contact_group_index
    contact-groups-grid:
        source:
            type: orm
            acl_resource: orocrm_contact_group_view
            query:
                select:
                    - g.id
                    - g.label
                from:
                  - { table: %orocrm_contact.group.entity.class%, alias: g }
        columns:
            label:
                label: Label
        properties:
            id: ~
            update_link:
                type:       url
                route:      orocrm_contact_group_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_contactgroup
                params:     [ id ]
        sorters:
            columns:
                label:
                    data_name: g.label
        filters:
            columns:
                label:
                    type:      string
                    data_name: g.label
        actions:
            update:
                type:          navigate
                acl_resource:  orocrm_contact_group_update
                label:         Update
                icon:          edit
                link:          update_link
                rowAction:     true
            delete:
                type:          delete
                acl_resource:  orocrm_contact_group_delete
                label:         Delete
                icon:          trash
                link:          delete_link
        options:
            entityHint: group
    # contacts assigned to group, shown on orocrm_contact_group_update route
    contact-group-contacts-grid:
        source:
            type: orm
            acl_resource: orocrm_contact_view
            query:
                select:
                    - c.id
                    - c.firstName
                    - c.lastName
                    - >
                      (CASE WHEN (:group IS NOT NULL) THEN
                        CASE WHEN (:group MEMBER OF c.groups OR c.id IN (:data_in)) AND c.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                      ELSE
                        CASE WHEN c.id IN (:data_in) AND c.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                      END) as hasGroup
                from:
                    - { table: %orocrm_contact.entity.class%, alias: c }
        columns:
            hasGroup:
                label: Has group
                editable: true
                frontend_type: boolean
            firstName:
                label: orocrm.contact.datagrid.first_name
            lastName:
                label: orocrm.contact.datagrid.last_name
        properties:
            id: ~
        filters:
            columns:
                hasGroup:
                    filter_by_having: true
                    data_name: hasGroup
                    type:  boolean
                firstName:
                    type: string
                    data_name: c.firstName
                lastName:
                    type: string
                    data_name: c.firstName
        sorters:
            columns:
                hasGroup:
                    data_name: hasGroup
                firstName:
                    data_name: c.firstName
                lastName:
                    data_name: c.lastName
            default: { hasGroup: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC }
        options:
            entityHint: contact
            requireJSModules:
                - oro/datagrid/column-form-listener
            columnListener:
                dataField: id
                columnName: hasGroup
                selectors:
                    included: '#groupAppendContacts'
                    excluded: '#groupRemoveContacts'
    # contacts main grid show on  orocrm_contact_index route
    contacts-grid:
        extended_entity_name: %orocrm_contact.entity.class%
        source:
            type: orm
            acl_resource: orocrm_contact_view
            query:
                select:
                    # selects full entity because group labels should be taken from object
                    - c
                    - contactSource.label as contactSourceLabel
                    - email.email as primaryEmail
                    - phone.phone as primaryPhone
                    - CONCAT(CASE WHEN address.stateText IS NOT NULL THEN address.stateText ELSE region.name END, '') as regionLabel
                    - country.name as countryName
                    - address.postalCode as addressPostalCode
                from:
                    - { table: %orocrm_contact.entity.class%, alias: c }
                join:
                    left:
                        - { join: c.addresses, alias: address, conditionType: WITH, condition: 'address.primary = true' }
                        - { join: c.emails, alias: email, conditionType: WITH, condition: 'email.primary = true' }
                        - { join: c.phones, alias: phone, conditionType: WITH, condition: 'phone.primary = true' }
                        - { join: c.groups, alias: contactGroup }
                        - { join: c.source, alias: contactSource }
                        - { join: address.country, alias: country }
                        - { join: address.state, alias: region }
        columns:
            firstName:
                label: orocrm.contact.datagrid.first_name
            lastName:
                label: orocrm.contact.datagrid.last_name
            primaryEmail:
                label: orocrm.contact.datagrid.email
            primaryPhone:
                label: orocrm.contact.datagrid.phone
            groupLabelsAsString:
                label: orocrm.contact.datagrid.groups
            contactSourceLabel:
                label: orocrm.contact.datagrid.source
            countryName:
                label: orocrm.contact.datagrid.country
            regionLabel:
                label: orocrm.contact.datagrid.region
            addressPostalCode:
                label: orocrm.contact.datagrid.postal_code
            createdAt:
                label: orocrm.contact.datagrid.created_at
                frontend_type: datetime
            updatedAt:
                label: orocrm.contact.datagrid.updated_at
                frontend_type: datetime
        properties:
            id: ~
            view_link:
                type:       url
                route:      orocrm_contact_view
                params:     [ id ]
            update_link:
                type:       url
                route:      orocrm_contact_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_contact
                params:     [ id ]
        sorters:
            columns:
                firstName:
                    data_name: c.firstName
                lastName:
                    data_name: c.lastName
                primaryEmail:
                    data_name: email.email
                primaryPhone:
                    data_name: phone.phone
                groupLabelsAsString:
                    data_name: contactGroup.label
                contactSourceLabel:
                    data_name: contactSource.label
                countryName:
                    data_name: country.name
                regionLabel:
                    data_name: regionLabel
                addressPostalCode:
                    data_name: address.postalCode
                createdAt:
                    data_name: c.createdAt
                updatedAt:
                    data_name: c.updatedAt
            default:
                firstName: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
                lastName:  %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        filters:
            columns:
                selectrow:
                    type: selectrow
                    label: orocrm.contact.datagrid.selected_rows
                    data_name: c.id
                firstName:
                    type: string
                    data_name: c.firstName
                lastName:
                    type: string
                    data_name: c.lastName
                primaryEmail:
                    type: string
                    data_name: email.email
                primaryPhone:
                    type: string
                    data_name: phone.phone
                groupLabelsAsString:
                    type: entity
                    data_name: contactGroup
                    enabled: false
                    options:
                        field_options:
                          class: OroCRMContactBundle:Group
                          property: label
                contactSourceLabel:
                    type: entity
                    data_name: contactSource
                    enabled: false
                    options:
                        field_options:
                          class: OroCRMContactBundle:Source
                          property: label
                countryName:
                    type: entity
                    data_name: address.country
                    enabled: false
                    options:
                        field_options:
                          class: OroAddressBundle:Country
                          property: name
                          query_builder: @orocrm_contact.contact.datagrid_helper->getCountryFilterQueryBuilder
                regionLabel:
                    type: string
                    data_name: regionLabel
                    enabled: false
                addressPostalCode:
                    type: string
                    data_name: addressPostalCode
                    enabled: false
                createdAt:
                    type:      datetime
                    data_name: c.createdAt
                updatedAt:
                    type:      datetime
                    data_name: c.updatedAt
                    enabled: false
        actions:
            view:
                type: navigate
                acl_resource: orocrm_contact_view
                label: orocrm.contact.datagrid.view
                icon: user
                link: view_link
                rowAction: true
            update:
                type: navigate
                acl_resource: orocrm_contact_update
                label: orocrm.contact.datagrid.update
                icon: edit
                link: update_link
            delete:
                type: delete
                acl_resource: orocrm_contact_delete
                label: orocrm.contact.datagrid.delete
                icon: trash
                link: delete_link
        mass_actions:
            delete:
                type: delete
                entity_name: %orocrm_contact.entity.class%
                data_identifier: c.id
                acl_resource: orocrm_contact_delete
                label: orocrm.contact.datagrid.delete
                icon: trash
        options:
            entityHint: contact

    # contact email datagrid
    contacts-email-grid:
        extend: email-grid
        source:
            query:
                where:
                    and:
                        - a.email IN (:email_addresses)

    # assigned accounts grid
    contact-accounts-grid:
        source:
            type: orm
            acl_resource: orocrm_contact_update
            query:
                select:
                    - a.id
                    - a.name
                    - a.createdAt
                    - a.updatedAt
                    - defaultContact.firstName as contactFirstName
                    - defaultContact.lastName as contactLastName
                    - defaultContactEmail.email as contactEmail
                    - defaultContactPhone.phone as contactPhone
                    - CONCAT(accountOwner.firstName, CONCAT(' ', accountOwner.lastName)) as ownerName
                    - >
                      (CASE WHEN (:contact IS NOT NULL) THEN
                        CASE WHEN (:contact MEMBER OF a.contacts OR a.id IN (:data_in)) AND a.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                      ELSE
                        CASE WHEN a.id IN (:data_in) AND a.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                      END) as hasContact
                from:
                    - { table: OroCRMAccountBundle:Account, alias: a }
                join:
                    left:
                        - { join: a.defaultContact, alias: defaultContact }
                        - { join: defaultContact.emails, alias: defaultContactEmail, conditionType: 'WITH', condition: 'defaultContactEmail.primary = true' }
                        - { join: defaultContact.phones, alias: defaultContactPhone, conditionType: 'WITH', condition: 'defaultContactPhone.primary = true' }
                        - { join: a.owner, alias: accountOwner }
        columns:
            hasContact:
                label:   Assigned
                editable: true
                frontend_type: boolean
            name:
                label:   orocrm.account.datagrid.account_name
            contactFirstName:
                label:   First Name
            contactLastName:
                label:   Last Name
            contactEmail:
                label:   Email
            contactPhone:
                label:   Phone
            ownerName:
                label:   Owner
            createdAt:
                label:   Created At
                frontend_type: datetime
            updatedAt:
                label:    Updated At
                frontend_type: datetime
        sorters:
            columns:
                hasContact:        { data_name: hasContact }
                name:              { data_name: a.name }
                contactFirstName:  { data_name: contactFirstName }
                contactLastName:   { data_name: contactLastName }
                contactEmail:      { data_name: contactEmail }
                contactPhone:      { data_name: contactPhone }
                ownerName:         { data_name: ownerName }
                createdAt:         { data_name: a.createdAt }
                updatedAt:         { data_name: a.updatedAt }
            default: { hasContact: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC }
        filters:
            columns:
                hasContact:
                    filter_by_having: true
                    data_name: hasContact
                    type:      boolean
                name:
                    type:      string
                    data_name: a.name
                contactFirstName:
                    type:      string
                    data_name: contactFirstName
                contactLastName:
                    type:      string
                    data_name: contactLastName
                contactEmail:
                    type:      string
                    data_name: contactEmail
                contactPhone:
                    type:      string
                    data_name: contactPhone
                ownerName:
                    type:      string
                    data_name: ownerName
                createdAt:
                    type:      datetime
                    data_name: a.createdAt
                updatedAt:
                    type:      datetime
                    data_name: a.updatedAt
        properties:
            id: ~
        options:
            entityHint: account
            requireJSModules:
              - oro/datagrid/column-form-listener
            columnListener:
                dataField: id
                columnName: hasContact
                selectors:
                    included: '#appendAccounts'
                    excluded: '#removeAccounts'
