parameters:
    oro_magento.event_listener.tracking_events_datagrid_listener.class: Oro\Bridge\MarketingCRM\EventListener\TrackingEventsDataGridListener
    oro_magento.provider.tracking_customer_identificator.class:         Oro\Bridge\MarketingCRM\Provider\TrackingCustomerIdentification
    oro_channel.listener.channel_repository_subscriber.class:           Oro\Bridge\MarketingCRM\EventListener\LoadClassMetadataSubscriber

services:
    oro_magento.event_listener.tracking_events_datagrid_listener:
        class: %oro_magento.event_listener.tracking_events_datagrid_listener.class%
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.pre.magento-customer-tracking-events-widget, method: onPreBuild, priority: 255 }

    oro_magento.provider.tracking_customer_identificator:
        class: %oro_magento.provider.tracking_customer_identificator.class%
        arguments:
           - "@doctrine"
           - "@oro_entity_config.provider.extend"
           - "@oro_channel.provider.settings_provider"
        tags:
           - {name: oro_tracking.provider.identification, priority: 10}

    oro_channel.listener.channel_repository_subscriber:
        class: %oro_channel.listener.channel_repository_subscriber.class%
        tags:
            - { name: doctrine.event_subscriber }

    oro_magento.provider.tracking_visit_precalculated.abstract:
        class: Oro\Bridge\MarketingCRM\Provider\AbstractPrecalculatedVisitProvider
        abstract: true
        arguments:
            - '@doctrine'
            - '@oro_config.global'
            - '@oro_security.acl_helper'

    oro_magento.provider.tracking_visit.precalculated:
        class: Oro\Bridge\MarketingCRM\Provider\PrecalculatedTrackingVisitProvider
        parent: oro_magento.provider.tracking_visit_precalculated.abstract
        decorates: oro_magento.provider.tracking_visit
        public: false
        calls:
            - ['setVisitProvider', ['@oro_magento.provider.tracking_visit.precalculated.inner']]
        tags:
            - { name: oro_featuretogle.feature, feature: 'tracking' }

    oro_magento.provider.website_visit.precalculated:
        class: Oro\Bridge\MarketingCRM\Provider\PrecalculatedWebsiteVisitProvider
        parent: oro_magento.provider.tracking_visit_precalculated.abstract
        decorates: oro_magento.provider.website_visit
        public: false
        calls:
            - ['setVisitProvider', ['@oro_magento.provider.website_visit.precalculated.inner']]
        tags:
            - { name: oro_featuretogle.feature, feature: 'tracking' }
