api:
    entities:
        Oro\Bundle\ContactBundle\Entity\Contact:
            fields:
                addresses:
                    collapse: false
                    fields:
                        owner:
                            exclude: true
