services:
    _instanceof:
        Oro\Component\MessageQueue\Client\TopicSubscriberInterface:
            tags:
                - { name: oro_message_queue.client.message_processor }

    oro_channel.async.aggregate_lifetime_average_processor:
        class: Oro\Bundle\ChannelBundle\Async\AggregateLifetimeAverageProcessor
        arguments:
            - '@doctrine'
            - '@oro_locale.settings'
            - '@oro_message_queue.job.runner'

    oro_channel.async.change_integration_status_processor:
        class: Oro\Bundle\ChannelBundle\Async\ChangeIntegrationStatusProcessor
        arguments:
            - '@doctrine'
            - '@oro_channel.provider.state_provider'
        calls:
            - [setLogger, ['@logger']]

    oro_channel.async.lifetime_history_update_processor:
        class: Oro\Bundle\ChannelBundle\Async\LifetimeHistoryStatusUpdateProcessor
        arguments:
            - '@doctrine'
