orocrm_marketing_list_bundle:
    resource:     "@OroCRMMarketingListBundle/Controller"
    type:         annotation
    prefix:       /

orocrm_marketing_list_api:
    resource:     "@OroCRMMarketingListBundle/Controller/Api/Rest/MarketingListController.php"
    type:         rest
    prefix:       api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest

orocrm_marketing_list_removed_item_api:
    resource:     "@OroCRMMarketingListBundle/Controller/Api/Rest/MarketingListRemovedItemController.php"
    type:         rest
    prefix:       api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest

orocrm_marketing_list_unsubscribed_item_api:
    resource:     "@OroCRMMarketingListBundle/Controller/Api/Rest/MarketingListUnsubscribedItemController.php"
    type:         rest
    prefix:       api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest

orocrm_marketing_list_segment_api:
    resource:     "@OroCRMMarketingListBundle/Controller/Api/Rest/SegmentController.php"
    type:         rest
    prefix:       api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest

# deprecated API routes
orocrm_api_post_marketinglist_removeditem_deprecated:
    path:            /api/rest/{version}/marketinglist/removeditem.{_format}
    methods:         [POST]
    defaults:
        _controller: OroCRM\Bundle\MarketingListBundle\Controller\Api\Rest\MarketingListRemovedItemController::postAction
        _format:     json
        version:     latest
    requirements:
        _format:     json|html
        version:     latest|v1

orocrm_api_post_marketinglist_segment_run_deprecated:
    path:            /api/rest/{version}/marketinglists/{id}/segment/run.{_format}
    methods:         [POST]
    defaults:
        _controller: OroCRM\Bundle\MarketingListBundle\Controller\Api\Rest\SegmentController::postRunAction
        _format:     json
        version:     latest
    requirements:
        _format:     json|html
        version:     latest|v1

orocrm_api_post_marketinglist_unsubscribeditem_deprecated:
    path:            /api/rest/{version}/marketinglist/unsubscribeditem.{_format}
    methods:         [POST]
    defaults:
        _controller: OroCRM\Bundle\MarketingListBundle\Controller\Api\Rest\MarketingListUnsubscribedItemController::postAction
        _format:     json
        version:     latest
    requirements:
        _format:     json|html
        version:     latest|v1
