services:
    oro_contact.tests.migration_listener:
        class: Oro\Bundle\ContactBundle\Tests\Functional\Environment\TestEntitiesMigrationListener
        tags:
            - { name: kernel.event_listener, event: oro_migration.post_up, method: onPostUp }

    oro_contact.tests.entity_name_resolver.data_loader:
        class: Oro\Bundle\ContactBundle\Tests\Functional\Environment\TestEntityNameResolverDataLoader
        decorates: oro_entity.tests.entity_name_resolver.data_loader
        arguments:
            - '@.inner'
