oro_menu_config:
    items:
        magento_cart:
            label:   'orocrm.magento.cart.entity_plural_label'
            route:   'orocrm_magento_cart_index'
            display: false
            extras:
                routes:      ['/^orocrm_magento_cart_(index|view)|orocrm_magento_orderplace_cart$/']
                position:    40
                description: 'orocrm.magento.cart.entity_plural_label'

        magento_order:
            label:   'orocrm.magento.order.entity_plural_label'
            route:   'orocrm_magento_order_index'
            display: false
            extras:
                routes:      ['/^orocrm_magento_order_(index|view)$/']
                position:    50
                description: 'orocrm.magento.order.entity_plural_label'

        magento_customer:
            label:   'orocrm.magento.customer.entity_plural_label'
            route:   'orocrm_magento_customer_index'
            display: false
            extras:
                routes:      ['/^orocrm_magento_customer_(index|view|create|update)$/']
                position:    60
                description: 'orocrm.magento.customer.entity_plural_label'

        magento_newsletter_subscriber:
            label:   'orocrm.magento.newslettersubscriber.entity_plural_label'
            route:   'orocrm_magento_newsletter_subscriber_index'
            display: false
            extras:
                routes:      ['/^orocrm_magento_newsletter_subscriber_(index|view)$/']
                position:    70
                description: 'orocrm.magento.newslettersubscriber.entity_plural_label'

    tree:
        application_menu:
            children:
                sales_tab:
                    children:
                        magento_cart: ~
                        magento_order: ~
                customers_tab:
                    children:
                        magento_customer: ~
                marketing_tab:
                    children:
                        magento_newsletter_subscriber: ~

oro_titles:
    orocrm_magento_customer_index: ~
    orocrm_magento_customer_view:  %%customer.name%%
    orocrm_magento_customer_update: %%customer.name%% - oro.ui.edit
    orocrm_magento_customer_create: oro.ui.create_entity

    orocrm_magento_cart_index:     ~
    orocrm_magento_cart_view:      'Cart #%%cart.id%%'

    orocrm_magento_order_index:    ~
    orocrm_magento_order_view:     'Order #%%order.incrementId%%'

    orocrm_magento_product_index:  'orocrm.magento.product.entity_plural_label'
    orocrm_magento_product_view:   %%product.name%%

    orocrm_magento_newsletter_subscriber_index:  'orocrm.magento.newslettersubscriber.entity_plural_label'
    orocrm_magento_newsletter_subscriber_view:   %%newsletter_subscriber.email%%
