<?php

namespace OroCRM\Bundle\ReportBundle\Datagrid\Accounts;

use Doctrine\ORM\EntityManager;

use Oro\Bundle\GridBundle\Datagrid\DatagridManager;
use Oro\Bundle\GridBundle\Datagrid\QueryConverter\YamlConverter;
use Oro\Bundle\GridBundle\Field\FieldDescriptionCollection;
use Symfony\Component\Yaml\Yaml;

class LifeTimeValueManager extends DatagridManager
{
    /** @var EntityManager */
    protected $em;

    public function __construct(EntityManager $em)
    {
        $this->em = $em;
    }

    protected function configureFields(FieldDescriptionCollection $fieldCollection)
    {
        parent::configureFields($fieldCollection); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    protected function createQuery()
    {
        $input     = Yaml::parse(file_get_contents(__DIR__ . '/../../Resources/config/reports.yml'));
        $converter = new YamlConverter();

        list($reportGroupName, $reportName) = array_slice(explode('-', $this->name), -2, 2);
        if (isset($input['reports'][$reportGroupName][$reportName])) {
            $this->queryFactory->setQueryBuilder(
                $converter->parse($input['reports']['accounts']['life_time_value'], $this->em)
            );
        }

        return $this->queryFactory->createQuery();
    }
}
