navigation:
    menu_config:
        items:
            sales_tab:
                label: 'oro.sales.menu.sales_tab.label'
                uri:   '#'
                position: 20
                extras:
                    icon: fa-shopping-cart

            lead_list:
                label: 'oro.sales.lead.entity_plural_label'
                route: 'oro_sales_lead_index'
                position: 20
                extras:
                    routes:      ['/^oro_sales_lead/']
                    description: 'oro.sales.menu.lead_list.description'

            opportunity_list:
                label: 'oro.sales.opportunity.entity_plural_label'
                route: 'oro_sales_opportunity_index'
                position: 30
                extras:
                    routes:      ['/^oro_sales_opportunity/']
                    description: 'oro.sales.menu.opportunity_list.description'

            b2bcustomer_list:
                label: 'oro.sales.b2bcustomer.entity_plural_label'
                route: 'oro_sales_b2bcustomer_index'
                display: false
                position: 70
                extras:
                    routes:      ['oro_sales_b2bcustomer_*']
                    description: 'oro.sales.menu.b2bcustomer_list.description'

            shortcut_list_b2bcustomers:
                label: 'oro.sales.menu.shortcut_list_b2bcustomers.label'
                route: 'oro_sales_lead_index'
                display: false
                extras:
                    description: 'oro.sales.menu.shortcut_list_b2bcustomers.description'

            shortcut_list_leads:
                label: 'oro.sales.menu.shortcut_list_leads.label'
                route: 'oro_sales_lead_index'
                display: false
                extras:
                    description: 'oro.sales.menu.shortcut_list_leads.description'

            shortcut_list_opportunities:
                label: 'oro.sales.menu.shortcut_list_opportunities.label'
                route: oro_sales_opportunity_index
                display: false
                extras:
                    description: 'oro.sales.menu.shortcut_list_opportunities.description'

            shortcut_new_lead:
                label: 'oro.sales.menu.shortcut_new_lead.label'
                route: 'oro_sales_lead_create'
                display: false
                extras:
                    description: 'oro.sales.menu.shortcut_new_lead.description'
                    isCustomAction: true

            shortcut_new_opportunity:
                label: 'oro.sales.menu.shortcut_new_opportunity.label'
                route: 'oro_sales_opportunity_create'
                display: false
                extras:
                    description: 'oro.sales.menu.shortcut_new_opportunity.description'
                    isCustomAction: true

        tree:
            application_menu:
                children:
                    sales_tab:
                        children:
                            lead_list: ~
                            opportunity_list: ~
                    customers_tab:
                         children:
                            b2bcustomer_list: ~
            shortcuts:
                children:
                    shortcut_list_leads: ~
                    shortcut_list_opportunities: ~
                    shortcut_new_lead: ~
                    shortcut_new_opportunity: ~

    titles:
        oro_sales_opportunity_index: ~
        oro_sales_opportunity_view: '%opportunity.name%'
        oro_sales_opportunity_create: 'Create Opportunity'
        oro_sales_opportunity_update: '%opportunity.name% - Edit'

        oro_sales_lead_index: ~
        oro_sales_lead_view: '%lead.name%'
        oro_sales_lead_create: 'Create Lead'
        oro_sales_lead_update: '%lead.name% - Edit'
        oro_sales_lead_convert_to_opportunity: '%lead.name% - Convert To Opportunity'

        oro_sales_b2bcustomer_index: ~
        oro_sales_b2bcustomer_view:   '%b2bcustomer.name%'
        oro_sales_b2bcustomer_create: 'Create Business Customer'
        oro_sales_b2bcustomer_update: '%b2bcustomer.name% - Edit'

    navigation_elements:
        pinButton:
            routes:
                oro_sales_lead_convert_to_opportunity: false
        favoriteButton:
            routes:
                oro_sales_lead_convert_to_opportunity: false
