system_configuration:
    groups:
        crm:
            icon:  fa-users
            title: oro.sales.system_configuration.groups.crm.title

        sales_pipeline:
            title: oro.sales.system_configuration.groups.sales_pipeline.title

        lead:
            icon:  fa-usd
            title: oro.sales.system_configuration.groups.lead.title

        opportunity:
            icon:  fa-usd
            title: oro.sales.system_configuration.groups.opportunity.title

        opportunity_status_probabilities:
            title: oro.sales.system_configuration.groups.opportunity_status_probabilities.title
            priority: 10

        display_settings:
            title: oro.sales.system_configuration.groups.display_settings.title
            priority: 20

    fields:
        oro_sales.lead_feature_enabled:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 20
            page_reload: true
            options:
                required: false
                label: oro.sales.system_configuration.fields.sales_lead.feature_enabled.label

        oro_sales.opportunity_feature_enabled:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 20
            page_reload: true
            options:
                required: false
                label: oro.sales.system_configuration.fields.sales_opportunity.feature_enabled.label

        oro_sales.opportunity_statuses:
            ui_only: true
            type: Oro\Bundle\SalesBundle\Form\Type\OpportunityStatusConfigType
            options:
                label: false
                required: false
                resettable: false
                attr:
                    class: oro-clearfix

        oro_sales.default_opportunity_probabilities:
            data_type: array
            type: Oro\Bundle\SalesBundle\Form\Type\OpportunityProbabilityType
            options:
                required: false
                resettable: true
                label: false
                allow_extra_fields: true
                attr:
                    class: oro-clearfix

        oro_sales.display_relevant_opportunities:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            page_reload: true
            options:
                required: false
                tooltip: oro.sales.system_configuration.fields.display_relevant_opportunities.tooltip
                label:   oro.sales.system_configuration.fields.display_relevant_opportunities.label
    tree:
        system_configuration:
            crm:
                children:
                    sales_pipeline:
                        children:
                            lead:
                                children:
                                    general_setup:
                                        children:
                                            - oro_sales.lead_feature_enabled
                            opportunity:
                                children:
                                    general_setup:
                                        priority: 100
                                        children:
                                            - oro_sales.opportunity_feature_enabled
                                    opportunity_status_probabilities:
                                        priority: 80
                                        children:
                                            - oro_sales.opportunity_statuses
                                    display_settings:
                                        priority: 70
                                        children:
                                            - oro_sales.display_relevant_opportunities
