<?php

namespace Oro\Bundle\ConfigBundle\DependencyInjection;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-15 at 15:07:49.
 */
class SettingsBuilderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SettingsBuilder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SettingsBuilder;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Oro\Bundle\ConfigBundle\DependencyInjection\SettingsBuilder::getNode
     * @todo   Implement testGetNode().
     */
    public function testGetNode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
