workflows:
    b2b_flow_sales:
        transition_definitions:
            qualify_definition:
                pre_conditions: # if opportunity.status = "in_progress"
                    '@equal': [$opportunity.status.id, 'in_progress']
            develop_definition:
                pre_conditions: # if opportunity.status = "in_progress"
                    '@and':
                        - '@equal':
                            message: 'Opportunity must be in status "In Progress"'
                            parameters: [$opportunity.status.id, 'in_progress']
                        - '@channel_entity_availiable': [$dataChannel, ['OroCRM\Bundle\SalesBundle\Entity\B2bCustomer']]
                conditions: # if opportunity.status = "in_progress"
                    '@and':
                        - '@greater_or_equal':
                            message: 'Budget amout must be greater or equal to 0'
                            parameters: [$budget_amount, 0]
                        - '@and':
                            message: 'Probality must be between 0 and 100 percents'
                            parameters:
                                - '@greater_or_equal': [$probability, 0]
                                - '@less_or_equal': [$probability, 1]
            close_as_won_definition:
                pre_conditions:
                    '@equal':
                        message: 'Opportunity must be in status "In Progress"'
                        parameters: [$opportunity.status.id, 'in_progress']
                conditions: # if opportunity.status = "in_progress", required data is entered and reason = "won"
                    '@and':
                        - '@not_empty':
                            message: 'Close date must be set'
                            parameters: $close_date
                        - '@not_empty':
                            message: 'Close revenue must be set'
                            parameters: $close_revenue
                        - '@greater_or_equal':
                            message: 'Close revenue must be greater or equal to 0'
                            parameters: [$close_revenue, 0]
                post_actions: # update opportunity properties, set opportunity.status = "won"
                    - '@request_enum_entity':
                        enum_code: opportunity_status
                        identifier: 'won'
                        attribute: $opportunity.status
                    - '@find_entity':
                        class: OroCRM\Bundle\SalesBundle\Entity\OpportunityCloseReason
                        identifier: 'won'
                        attribute: $close_reason
                    - '@assign_value':
                        - [$probability, 1]
                        - [$close_reason_name, 'won']
            close_as_lost_definition:
                pre_conditions: # opportunity.status = "in_progress", required data is entered and reason = "cancelled"
                    '@equal':
                        message: 'Opportunity must be in status "In Progress"'
                        parameters: [$opportunity.status.id, 'in_progress']
                conditions:
                    '@and':
                        - '@not_empty':
                            message: 'Close date must be set'
                            parameters: $close_date
                        - '@not_empty':
                            message: 'Close reason must be set'
                            parameters: $close_reason_name
                post_actions: # update opportunity properties, set opportunity.status = "lost"
                    - '@request_enum_entity':
                        enum_code: opportunity_status
                        identifier: 'lost'
                        attribute: $opportunity.status
                    - '@find_entity':
                        class: OroCRM\Bundle\SalesBundle\Entity\OpportunityCloseReason
                        identifier: $close_reason_name
                        attribute: $close_reason
                    - '@assign_value':
                        - [$probability, 0]
                        - [$close_revenue, 0]
            requalify_lost_definition:
                conditions:
                    '@equal': [$opportunity.status.id, 'lost']
                post_actions:
                    - '@request_enum_entity':
                        enum_code: opportunity_status
                        identifier: 'in_progress'
                        attribute: $opportunity.status
                    - '@assign_value':
                        - [$budget_amount, ~]
                        - [$probability, ~]
                        - [$close_reason, ~]
                        - [$close_date, ~]
                        - [$close_revenue, ~]
            requalify_won_definition:
                conditions:
                    '@equal': [$opportunity.status.id, 'won']
                post_actions:
                    - '@request_enum_entity':
                        enum_code: opportunity_status
                        identifier: 'in_progress'
                        attribute: $opportunity.status
