<?php

namespace OroCRM\Bundle\MagentoBundle\Migration\v1_0;

use Doctrine\DBAL\Schema\Schema;
use Oro\Bundle\InstallerBundle\Migrations\Migration;

class OroCRMMagentoBundle implements Migration
{
    /**
     * @inheritdoc
     */
    public function up(Schema $schema)
    {
        return [
            "CREATE TABLE orocrm_magento_cart (id INT AUTO_INCREMENT NOT NULL, channel_id SMALLINT DEFAULT NULL, workflow_item_id INT DEFAULT NULL, shipping_address_id INT DEFAULT NULL, status_name VARCHAR(32) DEFAULT NULL, workflow_step_id INT DEFAULT NULL, billing_address_id INT DEFAULT NULL, customer_id INT DEFAULT NULL, opportunity_id INT DEFAULT NULL, store_id INT DEFAULT NULL, items_qty INT UNSIGNED NOT NULL, items_count INT UNSIGNED NOT NULL, base_currency_code VARCHAR(32) NOT NULL, store_currency_code VARCHAR(32) NOT NULL, quote_currency_code VARCHAR(32) NOT NULL, store_to_base_rate DOUBLE PRECISION NOT NULL, store_to_quote_rate DOUBLE PRECISION DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, gift_message VARCHAR(255) DEFAULT NULL, is_guest TINYINT(1) NOT NULL, payment_details VARCHAR(255) DEFAULT NULL, notes LONGTEXT DEFAULT NULL, sub_total DOUBLE PRECISION DEFAULT NULL, grand_total DOUBLE PRECISION DEFAULT NULL, tax_amount DOUBLE PRECISION DEFAULT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, origin_id INT UNSIGNED DEFAULT NULL, UNIQUE INDEX UNIQ_96661A801023C4EE (workflow_item_id), UNIQUE INDEX unq_origin_id_channel_id (origin_id, channel_id), INDEX IDX_96661A809395C3F3 (customer_id), INDEX IDX_96661A80B092A811 (store_id), INDEX IDX_96661A804D4CFF2B (shipping_address_id), INDEX IDX_96661A8079D0C0E4 (billing_address_id), INDEX IDX_96661A806625D392 (status_name), INDEX IDX_96661A809A34590F (opportunity_id), INDEX IDX_96661A8071FE882C (workflow_step_id), INDEX IDX_96661A8072F5A1AA (channel_id), INDEX magecart_origin_idx (origin_id), PRIMARY KEY(id))",
            "CREATE TABLE orocrm_magento_cart_address (id INT AUTO_INCREMENT NOT NULL, region_code VARCHAR(16) DEFAULT NULL, country_code VARCHAR(2) DEFAULT NULL, `label` VARCHAR(255) DEFAULT NULL, street VARCHAR(500) NOT NULL, street2 VARCHAR(500) DEFAULT NULL, city VARCHAR(255) NOT NULL, postal_code VARCHAR(20) NOT NULL, organization VARCHAR(255) DEFAULT NULL, region_text VARCHAR(255) DEFAULT NULL, name_prefix VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, middle_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, name_suffix VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, origin_id INT UNSIGNED DEFAULT NULL, INDEX IDX_6978F651F026BB7C (country_code), INDEX IDX_6978F651AEB327AF (region_code), PRIMARY KEY(id))",
            "CREATE TABLE orocrm_magento_cart_calls (cart_id INT NOT NULL, call_id INT NOT NULL, INDEX IDX_83A847751AD5CDBF (cart_id), INDEX IDX_83A8477550A89B2C (call_id), PRIMARY KEY(cart_id, call_id))",
            "CREATE TABLE orocrm_magento_cart_emails (cart_id INT NOT NULL, email_id INT NOT NULL, INDEX IDX_11B0F84B1AD5CDBF (cart_id), INDEX IDX_11B0F84BA832C1C9 (email_id), PRIMARY KEY(cart_id, email_id))",
            "CREATE TABLE orocrm_magento_cart_item (id INT AUTO_INCREMENT NOT NULL, cart_id INT DEFAULT NULL, product_id INT UNSIGNED NOT NULL, parent_item_id INT UNSIGNED DEFAULT NULL, free_shipping VARCHAR(255) NOT NULL, gift_message VARCHAR(255) DEFAULT NULL, tax_class_id VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, is_virtual TINYINT(1) NOT NULL, custom_price DOUBLE PRECISION DEFAULT NULL, price_incl_tax DOUBLE PRECISION DEFAULT NULL, row_total DOUBLE PRECISION NOT NULL, tax_amount DOUBLE PRECISION NOT NULL, product_type VARCHAR(255) NOT NULL, sku VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, qty DOUBLE PRECISION NOT NULL, price DOUBLE PRECISION NOT NULL, discount_amount DOUBLE PRECISION NOT NULL, tax_percent DOUBLE PRECISION NOT NULL, weight DOUBLE PRECISION DEFAULT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, origin_id INT UNSIGNED DEFAULT NULL, INDEX IDX_A73DC8621AD5CDBF (cart_id), INDEX magecartitem_origin_idx (origin_id), INDEX magecartitem_sku_idx (sku), PRIMARY KEY(id))",
            "CREATE TABLE orocrm_magento_cart_status (name VARCHAR(32) NOT NULL, `label` VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_26317505EA750E8 (`label`), PRIMARY KEY(name))",
            "CREATE TABLE orocrm_magento_customer (id INT AUTO_INCREMENT NOT NULL, channel_id SMALLINT DEFAULT NULL, website_id INT DEFAULT NULL, account_id INT DEFAULT NULL, store_id INT DEFAULT NULL, customer_group_id INT DEFAULT NULL, contact_id INT DEFAULT NULL, name_prefix VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, middle_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, name_suffix VARCHAR(255) DEFAULT NULL, gender VARCHAR(8) DEFAULT NULL, birthday DATETIME DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, is_active TINYINT(1) NOT NULL, vat VARCHAR(255) DEFAULT NULL, origin_id INT UNSIGNED DEFAULT NULL, UNIQUE INDEX unq_origin_id_channel_id (origin_id, channel_id), INDEX IDX_2A61EE7D18F45C82 (website_id), INDEX IDX_2A61EE7DB092A811 (store_id), INDEX IDX_2A61EE7DD2919A68 (customer_group_id), INDEX IDX_2A61EE7DE7A1254A (contact_id), INDEX IDX_2A61EE7D9B6B5FBA (account_id), INDEX IDX_2A61EE7D72F5A1AA (channel_id), PRIMARY KEY(id))",
            "CREATE TABLE orocrm_magento_customer_address (id INT AUTO_INCREMENT NOT NULL, region_code VARCHAR(16) DEFAULT NULL, owner_id INT DEFAULT NULL, country_code VARCHAR(2) DEFAULT NULL, `label` VARCHAR(255) DEFAULT NULL, street VARCHAR(500) NOT NULL, street2 VARCHAR(500) DEFAULT NULL, city VARCHAR(255) NOT NULL, postal_code VARCHAR(20) NOT NULL, region_text VARCHAR(255) DEFAULT NULL, name_prefix VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, middle_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, name_suffix VARCHAR(255) DEFAULT NULL, is_primary TINYINT(1) DEFAULT NULL, organization VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, origin_id INT UNSIGNED DEFAULT NULL, INDEX IDX_55153CAD7E3C61F9 (owner_id), INDEX IDX_55153CADF026BB7C (country_code), INDEX IDX_55153CADAEB327AF (region_code), PRIMARY KEY(id))",
            "CREATE TABLE orocrm_magento_customer_address_to_address_type (customer_address_id INT NOT NULL, type_name VARCHAR(16) NOT NULL, INDEX IDX_65B2C97487EABF7 (customer_address_id), INDEX IDX_65B2C974892CBB0E (type_name), PRIMARY KEY(customer_address_id, type_name))",
            "CREATE TABLE orocrm_magento_customer_group (id INT AUTO_INCREMENT NOT NULL, channel_id SMALLINT DEFAULT NULL, name VARCHAR(255) NOT NULL, origin_id INT UNSIGNED DEFAULT NULL, INDEX IDX_71E09CA872F5A1AA (channel_id), PRIMARY KEY(id))",
            "CREATE TABLE orocrm_magento_order (id INT AUTO_INCREMENT NOT NULL, workflow_item_id INT DEFAULT NULL, cart_id INT DEFAULT NULL, workflow_step_id INT DEFAULT NULL, channel_id SMALLINT DEFAULT NULL, customer_id INT DEFAULT NULL, store_id INT DEFAULT NULL, increment_id VARCHAR(60) NOT NULL, is_virtual TINYINT(1) DEFAULT NULL, is_guest TINYINT(1) DEFAULT NULL, gift_message VARCHAR(255) DEFAULT NULL, remote_ip VARCHAR(255) DEFAULT NULL, store_name VARCHAR(255) DEFAULT NULL, total_paid_amount DOUBLE PRECISION DEFAULT NULL, total_invoiced_amount DOUBLE PRECISION DEFAULT NULL, total_refunded_amount DOUBLE PRECISION DEFAULT NULL, total_canceled_amount DOUBLE PRECISION DEFAULT NULL, notes LONGTEXT DEFAULT NULL, feedback LONGTEXT DEFAULT NULL, currency VARCHAR(10) DEFAULT NULL, payment_method VARCHAR(255) DEFAULT NULL, payment_details VARCHAR(255) DEFAULT NULL, subtotal_amount DOUBLE PRECISION DEFAULT NULL, shipping_amount DOUBLE PRECISION DEFAULT NULL, shipping_method VARCHAR(255) DEFAULT NULL, tax_amount DOUBLE PRECISION DEFAULT NULL, discount_amount DOUBLE PRECISION DEFAULT NULL, discount_percent DOUBLE PRECISION DEFAULT NULL, total_amount DOUBLE PRECISION DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_4D09F3051AD5CDBF (cart_id), UNIQUE INDEX UNIQ_4D09F3051023C4EE (workflow_item_id), UNIQUE INDEX unq_increment_id_channel_id (increment_id, channel_id), INDEX IDX_4D09F3059395C3F3 (customer_id), INDEX IDX_4D09F305B092A811 (store_id), INDEX IDX_4D09F30571FE882C (workflow_step_id), INDEX IDX_4D09F30572F5A1AA (channel_id), PRIMARY KEY(id))",
            "CREATE TABLE orocrm_magento_order_address (id INT AUTO_INCREMENT NOT NULL, region_code VARCHAR(16) DEFAULT NULL, owner_id INT DEFAULT NULL, country_code VARCHAR(2) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, street VARCHAR(500) NOT NULL, city VARCHAR(255) NOT NULL, postal_code VARCHAR(20) NOT NULL, organization VARCHAR(255) DEFAULT NULL, region_text VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, INDEX IDX_E31C6DEC7E3C61F9 (owner_id), INDEX IDX_E31C6DECF026BB7C (country_code), INDEX IDX_E31C6DECAEB327AF (region_code), PRIMARY KEY(id))",
            "CREATE TABLE orocrm_magento_order_address_to_address_type (order_address_id INT NOT NULL, type_name VARCHAR(16) NOT NULL, INDEX IDX_7B667960466D5220 (order_address_id), INDEX IDX_7B667960892CBB0E (type_name), PRIMARY KEY(order_address_id, type_name))",
            "CREATE TABLE orocrm_magento_order_calls (order_id INT NOT NULL, call_id INT NOT NULL, INDEX IDX_A885A348D9F6D38 (order_id), INDEX IDX_A885A3450A89B2C (call_id), PRIMARY KEY(order_id, call_id))",
            "CREATE TABLE orocrm_magento_order_emails (order_id INT NOT NULL, email_id INT NOT NULL, INDEX IDX_10E2A9508D9F6D38 (order_id), INDEX IDX_10E2A950A832C1C9 (email_id), PRIMARY KEY(order_id, email_id))",
            "CREATE TABLE orocrm_magento_order_items (id INT AUTO_INCREMENT NOT NULL, order_id INT DEFAULT NULL, product_type VARCHAR(255) DEFAULT NULL, product_options VARCHAR(255) DEFAULT NULL, is_virtual TINYINT(1) DEFAULT NULL, original_price DOUBLE PRECISION DEFAULT NULL, discount_percent DOUBLE PRECISION DEFAULT NULL, name VARCHAR(255) NOT NULL, sku VARCHAR(255) NOT NULL, qty INT NOT NULL, price DOUBLE PRECISION DEFAULT NULL, weight DOUBLE PRECISION DEFAULT NULL, tax_percent DOUBLE PRECISION DEFAULT NULL, tax_amount DOUBLE PRECISION DEFAULT NULL, discount_amount DOUBLE PRECISION DEFAULT NULL, row_total DOUBLE PRECISION DEFAULT NULL, origin_id INT UNSIGNED DEFAULT NULL, INDEX IDX_3135EFF68D9F6D38 (order_id), PRIMARY KEY(id))",
            "CREATE TABLE orocrm_magento_product (id INT AUTO_INCREMENT NOT NULL, channel_id SMALLINT DEFAULT NULL, name VARCHAR(255) NOT NULL, sku VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, special_price DOUBLE PRECISION DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, origin_id INT UNSIGNED NOT NULL, cost DOUBLE PRECISION DEFAULT NULL, UNIQUE INDEX unq_sku_channel_id (sku, channel_id), INDEX IDX_5A17298272F5A1AA (channel_id), PRIMARY KEY(id))",
            "CREATE TABLE orocrm_magento_product_to_website (product_id INT NOT NULL, website_id INT NOT NULL, INDEX IDX_3A3EF4984584665A (product_id), INDEX IDX_3A3EF49818F45C82 (website_id), PRIMARY KEY(product_id, website_id))",
            "CREATE TABLE orocrm_magento_region (id INT AUTO_INCREMENT NOT NULL, combined_code VARCHAR(60) NOT NULL, code VARCHAR(32) NOT NULL, country_code VARCHAR(255) NOT NULL, region_id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, UNIQUE INDEX unq_code (combined_code), INDEX idx_region (region_id), PRIMARY KEY(id))",
            "CREATE TABLE orocrm_magento_store (id INT AUTO_INCREMENT NOT NULL, channel_id SMALLINT DEFAULT NULL, website_id INT NOT NULL, store_code VARCHAR(32) NOT NULL, store_name VARCHAR(255) NOT NULL, origin_id INT UNSIGNED DEFAULT NULL, UNIQUE INDEX unq_code_channel_id (store_code, channel_id), INDEX IDX_477738EA18F45C82 (website_id), INDEX IDX_477738EA72F5A1AA (channel_id), PRIMARY KEY(id))",
            "CREATE TABLE orocrm_magento_website (id INT AUTO_INCREMENT NOT NULL, channel_id SMALLINT DEFAULT NULL, website_code VARCHAR(32) NOT NULL, website_name VARCHAR(255) NOT NULL, origin_id INT UNSIGNED DEFAULT NULL, UNIQUE INDEX unq_site_idx (website_code, origin_id, channel_id), INDEX IDX_CE3270C872F5A1AA (channel_id), PRIMARY KEY(id))",

            "ALTER TABLE orocrm_magento_cart ADD CONSTRAINT FK_96661A8072F5A1AA FOREIGN KEY (channel_id) REFERENCES oro_integration_channel (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_cart ADD CONSTRAINT FK_96661A801023C4EE FOREIGN KEY (workflow_item_id) REFERENCES oro_workflow_item (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_cart ADD CONSTRAINT FK_96661A804D4CFF2B FOREIGN KEY (shipping_address_id) REFERENCES orocrm_magento_cart_address (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_cart ADD CONSTRAINT FK_96661A806625D392 FOREIGN KEY (status_name) REFERENCES orocrm_magento_cart_status (name) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_cart ADD CONSTRAINT FK_96661A8071FE882C FOREIGN KEY (workflow_step_id) REFERENCES oro_workflow_step (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_cart ADD CONSTRAINT FK_96661A8079D0C0E4 FOREIGN KEY (billing_address_id) REFERENCES orocrm_magento_cart_address (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_cart ADD CONSTRAINT FK_96661A809395C3F3 FOREIGN KEY (customer_id) REFERENCES orocrm_magento_customer (id) ON DELETE CASCADE",
            "ALTER TABLE orocrm_magento_cart ADD CONSTRAINT FK_96661A809A34590F FOREIGN KEY (opportunity_id) REFERENCES orocrm_sales_opportunity (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_cart ADD CONSTRAINT FK_96661A80B092A811 FOREIGN KEY (store_id) REFERENCES orocrm_magento_store (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_cart_address ADD CONSTRAINT FK_6978F651AEB327AF FOREIGN KEY (region_code) REFERENCES oro_dictionary_region (combined_code)",
            "ALTER TABLE orocrm_magento_cart_address ADD CONSTRAINT FK_6978F651F026BB7C FOREIGN KEY (country_code) REFERENCES oro_dictionary_country (iso2_code)",
            "ALTER TABLE orocrm_magento_cart_calls ADD CONSTRAINT FK_83A8477550A89B2C FOREIGN KEY (call_id) REFERENCES orocrm_call (id)",
            "ALTER TABLE orocrm_magento_cart_calls ADD CONSTRAINT FK_83A847751AD5CDBF FOREIGN KEY (cart_id) REFERENCES orocrm_magento_cart (id)",
            "ALTER TABLE orocrm_magento_cart_emails ADD CONSTRAINT FK_11B0F84BA832C1C9 FOREIGN KEY (email_id) REFERENCES oro_email (id)",
            "ALTER TABLE orocrm_magento_cart_emails ADD CONSTRAINT FK_11B0F84B1AD5CDBF FOREIGN KEY (cart_id) REFERENCES orocrm_magento_cart (id)",
            "ALTER TABLE orocrm_magento_cart_item ADD CONSTRAINT FK_A73DC8621AD5CDBF FOREIGN KEY (cart_id) REFERENCES orocrm_magento_cart (id) ON DELETE CASCADE",
            "ALTER TABLE orocrm_magento_customer ADD CONSTRAINT FK_2A61EE7D72F5A1AA FOREIGN KEY (channel_id) REFERENCES oro_integration_channel (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_customer ADD CONSTRAINT FK_2A61EE7D18F45C82 FOREIGN KEY (website_id) REFERENCES orocrm_magento_website (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_customer ADD CONSTRAINT FK_2A61EE7D9B6B5FBA FOREIGN KEY (account_id) REFERENCES orocrm_account (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_customer ADD CONSTRAINT FK_2A61EE7DB092A811 FOREIGN KEY (store_id) REFERENCES orocrm_magento_store (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_customer ADD CONSTRAINT FK_2A61EE7DD2919A68 FOREIGN KEY (customer_group_id) REFERENCES orocrm_magento_customer_group (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_customer ADD CONSTRAINT FK_2A61EE7DE7A1254A FOREIGN KEY (contact_id) REFERENCES orocrm_contact (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_customer_address ADD CONSTRAINT FK_55153CADAEB327AF FOREIGN KEY (region_code) REFERENCES oro_dictionary_region (combined_code)",
            "ALTER TABLE orocrm_magento_customer_address ADD CONSTRAINT FK_55153CAD7E3C61F9 FOREIGN KEY (owner_id) REFERENCES orocrm_magento_customer (id) ON DELETE CASCADE",
            "ALTER TABLE orocrm_magento_customer_address ADD CONSTRAINT FK_55153CADF026BB7C FOREIGN KEY (country_code) REFERENCES oro_dictionary_country (iso2_code)",
            "ALTER TABLE orocrm_magento_customer_address_to_address_type ADD CONSTRAINT FK_65B2C974892CBB0E FOREIGN KEY (type_name) REFERENCES oro_address_type (name)",
            "ALTER TABLE orocrm_magento_customer_address_to_address_type ADD CONSTRAINT FK_65B2C97487EABF7 FOREIGN KEY (customer_address_id) REFERENCES orocrm_magento_customer_address (id) ON DELETE CASCADE",
            "ALTER TABLE orocrm_magento_customer_group ADD CONSTRAINT FK_71E09CA872F5A1AA FOREIGN KEY (channel_id) REFERENCES oro_integration_channel (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_order ADD CONSTRAINT FK_4D09F3051023C4EE FOREIGN KEY (workflow_item_id) REFERENCES oro_workflow_item (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_order ADD CONSTRAINT FK_4D09F3051AD5CDBF FOREIGN KEY (cart_id) REFERENCES orocrm_magento_cart (id)",
            "ALTER TABLE orocrm_magento_order ADD CONSTRAINT FK_4D09F30571FE882C FOREIGN KEY (workflow_step_id) REFERENCES oro_workflow_step (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_order ADD CONSTRAINT FK_4D09F30572F5A1AA FOREIGN KEY (channel_id) REFERENCES oro_integration_channel (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_order ADD CONSTRAINT FK_4D09F3059395C3F3 FOREIGN KEY (customer_id) REFERENCES orocrm_magento_customer (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_order ADD CONSTRAINT FK_4D09F305B092A811 FOREIGN KEY (store_id) REFERENCES orocrm_magento_store (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_order_address ADD CONSTRAINT FK_E31C6DECAEB327AF FOREIGN KEY (region_code) REFERENCES oro_dictionary_region (combined_code)",
            "ALTER TABLE orocrm_magento_order_address ADD CONSTRAINT FK_E31C6DEC7E3C61F9 FOREIGN KEY (owner_id) REFERENCES orocrm_magento_order (id) ON DELETE CASCADE",
            "ALTER TABLE orocrm_magento_order_address ADD CONSTRAINT FK_E31C6DECF026BB7C FOREIGN KEY (country_code) REFERENCES oro_dictionary_country (iso2_code)",
            "ALTER TABLE orocrm_magento_order_address_to_address_type ADD CONSTRAINT FK_7B667960892CBB0E FOREIGN KEY (type_name) REFERENCES oro_address_type (name)",
            "ALTER TABLE orocrm_magento_order_address_to_address_type ADD CONSTRAINT FK_7B667960466D5220 FOREIGN KEY (order_address_id) REFERENCES orocrm_magento_order_address (id) ON DELETE CASCADE",
            "ALTER TABLE orocrm_magento_order_calls ADD CONSTRAINT FK_A885A3450A89B2C FOREIGN KEY (call_id) REFERENCES orocrm_call (id)",
            "ALTER TABLE orocrm_magento_order_calls ADD CONSTRAINT FK_A885A348D9F6D38 FOREIGN KEY (order_id) REFERENCES orocrm_magento_order (id)",
            "ALTER TABLE orocrm_magento_order_emails ADD CONSTRAINT FK_10E2A950A832C1C9 FOREIGN KEY (email_id) REFERENCES oro_email (id)",
            "ALTER TABLE orocrm_magento_order_emails ADD CONSTRAINT FK_10E2A9508D9F6D38 FOREIGN KEY (order_id) REFERENCES orocrm_magento_order (id)",
            "ALTER TABLE orocrm_magento_order_items ADD CONSTRAINT FK_3135EFF68D9F6D38 FOREIGN KEY (order_id) REFERENCES orocrm_magento_order (id) ON DELETE CASCADE",
            "ALTER TABLE orocrm_magento_product ADD CONSTRAINT FK_5A17298272F5A1AA FOREIGN KEY (channel_id) REFERENCES oro_integration_channel (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_product_to_website ADD CONSTRAINT FK_3A3EF49818F45C82 FOREIGN KEY (website_id) REFERENCES orocrm_magento_website (id) ON DELETE CASCADE",
            "ALTER TABLE orocrm_magento_product_to_website ADD CONSTRAINT FK_3A3EF4984584665A FOREIGN KEY (product_id) REFERENCES orocrm_magento_product (id) ON DELETE CASCADE",
            "ALTER TABLE orocrm_magento_store ADD CONSTRAINT FK_477738EA72F5A1AA FOREIGN KEY (channel_id) REFERENCES oro_integration_channel (id) ON DELETE SET NULL",
            "ALTER TABLE orocrm_magento_store ADD CONSTRAINT FK_477738EA18F45C82 FOREIGN KEY (website_id) REFERENCES orocrm_magento_website (id) ON DELETE CASCADE",
            "ALTER TABLE orocrm_magento_website ADD CONSTRAINT FK_CE3270C872F5A1AA FOREIGN KEY (channel_id) REFERENCES oro_integration_channel (id) ON DELETE SET NULL"
        ];
    }
}
