workflows:
    opportunity_flow:
        transition_definitions:
            create_definition:
                actions:
                    - '@create_object':
                        class: Oro\Bundle\CurrencyBundle\Entity\MultiCurrency
                        attribute: $close_revenue
                    - '@assign_value':
                        - [$close_reason, null]
            develop_definition:
                conditions:
                    '@and':
                        - '@neq': [$status.internalId, 'lost']
                        - '@neq': [$status.internalId, 'won']
            close_won_definition:
                conditions:
                    '@not_empty':
                        message: 'Close date must be set'
                        parameters: $close_date
                actions:
                    - '@request_enum_entity':
                        enum_code: opportunity_status
                        identifier: 'opportunity_status.won'
                        attribute: $opportunity.status
                    - '@find_entity':
                        class: Oro\Bundle\SalesBundle\Entity\OpportunityCloseReason
                        identifier: 'won'
                        attribute: $close_reason
                    - '@assign_value':
                        - [$close_reason_name, 'won']
                    - '@call_service_method':
                        service: oro_sales.provider.probability
                        method: get
                        method_parameters: [$opportunity.status]
                        attribute: $opportunity.probability
            close_lost_definition:
                conditions:
                    '@and':
                        - '@not_empty':
                            message: 'Close date must be set'
                            parameters: $close_date
                        - '@not_empty':
                            message: 'Close reason must be set'
                            parameters: $close_reason_name
                actions:
                    - '@request_enum_entity':
                        enum_code: opportunity_status
                        identifier: 'opportunity_status.lost'
                        attribute: $opportunity.status
                    - '@find_entity':
                        class: Oro\Bundle\SalesBundle\Entity\OpportunityCloseReason
                        identifier: $close_reason_name
                        attribute: $close_reason
                    - '@call_service_method':
                        service: oro_currency.config.currency
                        method: getDefaultCurrency
                        attribute: $.result.currency
                    - '@create_object':
                        class: Oro\Bundle\CurrencyBundle\Entity\MultiCurrency
                        attribute: $.result.close_revenue
                    - '@assign_value': [$.result.close_revenue.value, 0]
                    - '@assign_value': [$.result.close_revenue.currency, $.result.currency]
                    - '@assign_value':
                        - [$close_revenue, $.result.close_revenue]
                    - '@call_service_method':
                        service: oro_sales.provider.probability
                        method: get
                        method_parameters: [$opportunity.status]
                        attribute: $opportunity.probability
            reopen_definition:
                conditions:
                    '@and':
                        - '@neq': [$status.internalId, 'lost']
                        - '@neq': [$status.internalId, 'won']
                actions:
                    - '@create_object':
                        class: Oro\Bundle\CurrencyBundle\Entity\MultiCurrency
                        attribute: $close_revenue
                    - '@assign_value':
                        - [$close_reason, null]
