datagrids:
    base-case-grid:
        acl_resource: oro_case_view
        source:
            type: orm
            query:
                select:
                    - caseEntity.id
                    - caseEntity.id as caseNumber
                    - caseEntity.subject
                    - caseEntity.reportedAt
                    - caseEntity.closedAt
                    - CONCAT_WS(' ', relatedContact.firstName, relatedContact.lastName) as relatedContactName
                    - CONCAT_WS(' ', assignedTo.firstName, assignedTo.lastName) as assignedToName
                    - relatedAccount.name as relatedAccountName
                    - assignedTo.id as assignedToId
                    - status.label as statusLabel
                    - pr.label as priorityLabel
                    - pr.name as priority
                from:
                    - { table: 'Oro\Bundle\CaseBundle\Entity\CaseEntity', alias: caseEntity }
                join:
                    left:
                        - { join: caseEntity.relatedContact, alias: relatedContact }
                        - { join: caseEntity.relatedAccount, alias: relatedAccount }
                        - { join: caseEntity.assignedTo, alias: assignedTo }
                        - { join: caseEntity.owner, alias: owner }
                        - { join: caseEntity.source, alias: source }
                        - { join: caseEntity.status, alias: status }
                        - { join: caseEntity.priority, alias: pr }
        inline_editing:
            enable: true
            entity_name: 'Oro\Bundle\CaseBundle\Entity\CaseEntity'
        columns:
            caseNumber:
                label: oro.case.datagrid.case_number.label
            subject:
                inline_editing:
                    enable: false
                type: twig
                label: oro.case.datagrid.subject.label
                frontend_type: html
                template: '@OroCase/Case/Datagrid/Property/subject.html.twig'
            assignedToName:
                type: twig
                label: oro.case.datagrid.assigned_to.label
                frontend_type: html
                template: '@OroCase/Case/Datagrid/Property/assignedTo.html.twig'
            reportedAt:
                inline_editing:
                    enable: false
                label: oro.case.datagrid.reported_on.label
                frontend_type: datetime
            closedAt:
                inline_editing:
                    enable: false
                label: oro.case.datagrid.closed_on.label
                frontend_type: datetime
            statusLabel:
                label: oro.case.datagrid.status.label
            priority:
                label: oro.case.datagrid.priority.label
        sorters:
            columns:
                subject:
                    data_name: caseEntity.subject
                caseNumber:
                    data_name: caseEntity.id
                assignedToName:
                    data_name: assignedToName
                reportedAt:
                    data_name: caseEntity.reportedAt
                closedAt:
                    data_name: caseEntity.closedAt
                statusLabel:
                    data_name: status.order
                priority:
                    data_name: pr.order
            default:
                reportedAt: DESC
        filters:
            columns:
                caseNumber:
                    type: number-range
                    data_name: caseEntity.id
                subject:
                    type: string
                    data_name: caseEntity.subject
                assignedToName:
                    type: string
                    data_name: assignedToName
                reportedAt:
                    type: datetime
                    data_name: caseEntity.reportedAt
                closedAt:
                    type: datetime
                    data_name: caseEntity.closedAt
                statusLabel:
                    label: oro.case.datagrid.status.label
                    type: entity
                    data_name: status.name
                    options:
                        field_options:
                            class: Oro\Bundle\CaseBundle\Entity\CaseStatus
                            choice_label: label
                priorityLabel:
                    label: oro.case.datagrid.priority.label
                    type: entity
                    data_name: pr.name
                    options:
                        field_options:
                            class: Oro\Bundle\CaseBundle\Entity\CasePriority
                            choice_label: label
                source:
                    label: oro.case.datagrid.source.label
                    type: entity
                    renderable: false
                    data_name: source.name
                    options:
                        field_options:
                            class: Oro\Bundle\CaseBundle\Entity\CaseSource
                            choice_label: label
                owner:
                    type: choice-tree
                    label: oro.user.owner.label
                    data_name: caseEntity.owner
                    autocomplete_alias: assigned_to_organization_users
                    renderedPropertyName: 'fullName'
                    className: 'Oro\Bundle\UserBundle\Entity\User'
                    renderable: false
                businessUnitId:
                    label: oro.business_unit.label
                    type: choice-business-unit
                    data_name: caseEntity.owner
                    className: 'Oro\Bundle\OrganizationBundle\Entity\BusinessUnit'
                    renderable: false
        properties:
            id: ~
            view_link:
                type:         url
                route:        oro_case_view
                params:       [ id ]
            update_link:
                type:         url
                route:        oro_case_update
                params:       [ id ]
            delete_link:
                type:         url
                route:        oro_case_api_delete_case
                params:       [ id ]
        actions:
            view:
                type:         navigate
                acl_resource: oro_case_view
                label:        oro.grid.action.view
                icon:         eye
                link:         view_link
                rowAction:    true
            update:
                type:         navigate
                acl_resource: oro_case_update
                label:        oro.grid.action.update
                icon:         edit
                link:         update_link
            delete:
                type:         delete
                acl_resource: oro_case_delete
                label:        oro.grid.action.delete
                icon:         trash
                link:         delete_link

    base-cases-with-relations-grid:
        extends: base-case-grid
        filters:
            columns:
                relatedContact:
                    label: oro.case.datagrid.related_contact.label
                    type: string
                    data_name: relatedContactName
                    renderable: false
                relatedAccount:
                    label: oro.case.datagrid.related_account.label
                    type: string
                    data_name: relatedAccountName
                    renderable: false
        options:
            entity_pagination: true

    cases-grid:
        extends: base-cases-with-relations-grid
        extended_entity_name: 'Oro\Bundle\CaseBundle\Entity\CaseEntity'

    account-cases-grid:
        extends: base-case-grid
        filters:
            columns:
                relatedContact:
                    label: oro.case.datagrid.related_contact.label
                    type: string
                    data_name: relatedContactName
                    renderable: false
        source:
            query:
                where:
                    and:
                        - relatedAccount.id = :id
            bind_parameters:
                - id

    contact-cases-grid:
        extends: base-case-grid
        filters:
            columns:
                relatedAccount:
                    label: oro.case.datagrid.related_account.label
                    type: string
                    data_name: relatedAccountName
                    renderable: false
        source:
            query:
                where:
                    and:
                        - relatedContact.id = :id
            bind_parameters:
                - id

    user-cases-grid:
        extends: base-cases-with-relations-grid
        source:
            query:
                where:
                    and:
                        - (assignedTo.id = :id OR owner.id = :id)
            bind_parameters:
                - id
        options:
            entity_pagination: false

    cases-for-context-grid:
        options:
            toolbarOptions:
                pageSize:
                    default_per_page: 10
            routerEnabled: false
        acl_resource: oro_case_view
        source:
            type: orm
            query:
                select:
                    - caseEntity.id
                    - caseEntity.id as caseNumber
                    - caseEntity.subject
                    - caseEntity.reportedAt
                    - CONCAT_WS(' ', relatedContact.firstName, relatedContact.lastName) as relatedContactName
                    - CONCAT_WS(' ', assignedTo.firstName, assignedTo.lastName) as assignedToName
                    - relatedAccount.name as relatedAccountName
                    - assignedTo.id as assignedToId
                    - status.label as statusLabel
                    - priority.label as priorityLabel
                from:
                    - { table: 'Oro\Bundle\CaseBundle\Entity\CaseEntity', alias: caseEntity }
                join:
                    left:
                        - { join: caseEntity.relatedContact, alias: relatedContact }
                        - { join: caseEntity.relatedAccount, alias: relatedAccount }
                        - { join: caseEntity.assignedTo, alias: assignedTo }
                        - { join: caseEntity.owner, alias: owner }
                        - { join: caseEntity.source, alias: source }
                        - { join: caseEntity.status, alias: status }
                        - { join: caseEntity.priority, alias: priority }
        columns:
            id:
                label: oro.case.datagrid.id.label
            subject:
                type: twig
                label: oro.case.datagrid.subject.label
                frontend_type: html
                template: '@OroCase/Case/Datagrid/Property/subject.html.twig'
            assignedToName:
                type: twig
                label: oro.case.datagrid.assigned_to.label
                frontend_type: html
                template: '@OroCase/Case/Datagrid/Property/assignedTo.html.twig'
            statusLabel:
                label: oro.case.datagrid.status.label
            priorityLabel:
                label: oro.case.datagrid.priority.label
            reportedAt:
                renderable: false
                frontend_type: datetime
        sorters:
            columns:
                subject:
                    data_name: caseEntity.subject
                assignedToName:
                    data_name: assignedToName
                statusLabel:
                    data_name: status.order
                priorityLabel:
                    data_name: priority.order
                reportedAt:
                    data_name: caseEntity.reportedAt
            default:
                reportedAt: DESC
        filters:
            columns:
                subject:
                    type: string
                    data_name: caseEntity.subject
                assignedToName:
                    type: string
                    data_name: assignedToName
                statusLabel:
                    label: oro.case.datagrid.status.label
                    type: entity
                    data_name: status.name
                    options:
                        field_options:
                            class: Oro\Bundle\CaseBundle\Entity\CaseStatus
                            choice_label: label
                priorityLabel:
                    label: oro.case.datagrid.priority.label
                    type: entity
                    data_name: priority.name
                    options:
                        field_options:
                            class: Oro\Bundle\CaseBundle\Entity\CasePriority
                            choice_label: label
